---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd.git
    augeas_core: https://github.com/puppetlabs/puppetlabs-augeas_core.git
    augeasproviders_core: https://github.com/simp/augeasproviders_core.git
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub.git
    cron_core: https://github.com/puppetlabs/puppetlabs-cron_core.git
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup.git
    concat: https://github.com/simp/puppetlabs-concat.git
    simp_options: https://github.com/simp/pupmod-simp-simp_options.git
    logrotate: https://github.com/simp/pupmod-simp-logrotate.git
    pki: https://github.com/simp/pupmod-simp-pki.git
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog.git
    simplib: https://github.com/simp/pupmod-simp-simplib.git
    stdlib: https://github.com/simp/puppetlabs-stdlib.git
    systemd: https://github.com/simp/puppet-systemd.git
    disa_stig-el7-baseline:
      repo: https://github.com/simp/inspec-profile-disa_stig-el7.git
      branch: master
      target: spec/fixtures/inspec_deps/inspec_profiles/profiles
  symlinks:
    aide: "#{source_dir}"
