---
fixtures:
  repositories:
    auditd:
      repo: https://github.com/simp/pupmod-simp-auditd
      branch: 5.X
    augeasproviders_core:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_core
    augeasproviders_grub:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_grub
    compliance_markup:
      repo: https://github.com/simp/pupmod-simp-compliance_markup
      branch: 5.X
    logrotate:
      repo: https://github.com/simp/pupmod-simp-logrotate
      branch: 5.X
    pki:
      repo: https://github.com/simp/pupmod-simp-pki
      branch: 5.X
    rsyslog:
      repo: https://github.com/simp/pupmod-simp-rsyslog
      branch: 5.X
    simpcat:
      repo: https://github.com/simp/pupmod-simp-simpcat
      branch: 5.X
    simplib:
      repo: https://github.com/simp/pupmod-simp-simplib
      branch: 5.X
    stdlib:
      branch: 5.X
      repo: https://github.com/simp/puppetlabs-stdlib
  symlinks:
    aide: "#{source_dir}"
