---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    pki: https://github.com/simp/pupmod-simp-pki
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    systemd:
      repo: https://github.com/simp/puppet-systemd
      branch: simp-master
    disa_stig-el7-baseline:
      repo: https://github.com/simp/inspec-profile-disa_stig-el7
      branch:  master
      target: spec/fixtures/inspec_deps/inspec_profiles/profiles
  symlinks:
    aide: "#{source_dir}"
