---
fixtures:
  repositories:
    auditd: "git://github.com/simp/pupmod-simp-auditd"
    augeasproviders_core: "git://github.com/simp/augeasproviders_core"
    augeasproviders_grub: "git://github.com/simp/augeasproviders_grub"
    common: "git://github.com/simp/pupmod-simp-common"
    simplib: "git://github.com/simp/pupmod-simp-simplib"
    simpcat: "git://github.com/simp/pupmod-simp-concat"
    functions: "git://github.com/simp/pupmod-simp-functions"
    logrotate: "git://github.com/simp/pupmod-simp-logrotate"
    pki: "git://github.com/simp/pupmod-simp-pki"
    rsyslog: "git://github.com/simp/pupmod-simp-rsyslog"
    stdlib: "git://github.com/simp/puppetlabs-stdlib"
  symlinks:
    aide: "#{source_dir}"
