<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el6:
    roles:
      - server
      - default
      - master
      - client
    platform: el-6-x86_64
    box: centos/6
    hypervisor: <%= hypervisor %>
  el7:
    roles:
      - client
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>

CONFIG:
  log_level: verbose
  synced_folder : disabled
  type: aio
  vagrant_memsize: 256
<% if ENV['BEAKER_PUPPET_ENVIRONMENT'] -%>
  puppet_environment: <%= ENV['BEAKER_PUPPET_ENVIRONMENT'] %>
<% end -%>
