<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el7:
    roles:
      - client
      # roles migrated from now-removed el6 node(s): 
      - server
      - default
      - master
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>
    yum_repos:
      chef-current:
        baseurl: 'https://packages.chef.io/repos/yum/current/el/7/$basearch'
        gpgkeys:
          - https://packages.chef.io/chef.asc
  el8:
    roles:
      - client
    platform: el-8-x86_64
    box: centos/8
    hypervisor: <%= hypervisor %>
    yum_repos:
      chef-current:
        baseurl: 'https://packages.chef.io/repos/yum/current/el/8/$basearch'
        gpgkeys:
          - https://packages.chef.io/chef.asc
CONFIG:
  log_level: verbose
  synced_folder : disabled
  type: aio
  vagrant_memsize: 256
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
