---
HOSTS:
  el9:
    roles:
    - client
    - server
    - default
    - master
    platform: el-9-x86_64
    box: generic/centos9s
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    family: centos-cloud/centos-stream-9
    gce_machine_type: n1-standard-2
  el8:
    roles:
    - client
    platform: el-8-x86_64
    box: generic/centos8
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    family: centos-cloud/centos-stream-8
    gce_machine_type: n1-standard-2
CONFIG:
  log_level: verbose
  synced_folder: disabled
  type: aio
  vagrant_cpus: 2
  puppet_collection: "<%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'puppet7') %>"
